### ISSUE TITLE
Pixel scan effect?

### ISSUE THREAD

**Issue by fredm00n** [fand/vfx-js#92]
Thanks a lot for this awesome library! Super grateful for your work.

I didn't know where else to ask: is a Pixel Scan effect possible to implement? Something similar to what we often see in After Effect and/or Blender 3D, like on this YouTube tutorial for example https://www.youtube.com/watch?v=JFn2kK8GhUQ

Many thanks!
fred

**Comment by fand** [comment]
Hi @fredm00n ! Thx for checking VFX-JS 🙏 
I saw video, it seems that it's totally possible. 
I'm gonna try making the effect on Codepen in a few days, will post it here.

**Comment by fand** [comment]
Hi @fredm00n !  I've just posted a sample on Codepen. 
https://codepen.io/fand/pen/MWMBdbj

https://github.com/user-attachments/assets/9f541018-2887-447e-9030-927bf44b81ce


The glow effect is actually a bit difficult to implement, so instead I layered multiple pixel effects for the aesthetics.
You can adjust the animation by changing these parameter:

```js
  vfx.add(e, { 
    shader, 
    overflow: 30, 
    intersection: { threshold: 0.99 },
    uniforms: {      
      
      // Animation mode.
      // - 0: left-to-right
      // - 1: top-to-bottom
      // - 2: radial       
      mode: data.mode ?? 0,
      
      // Width of effect area.
      width: data.width ?? 0.2,
      
      // Number of pixel layers.
      layers: data.layers ?? 3,
            
      speed: data.speed ?? 1, 
      delay: data.delay ?? 0,      
      
    }
  });  
```

I hope this will help you 😸

**Comment by fredm00n** [comment]
You are an absolute genius. This is such a perfect effect. I love this! Thank you so very much.
